# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/dudl/?couponCode=202201

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [3]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[-0.08  3.06 -0.46  1.41  3.55]
 [-0.18 -2.04  1.2  -0.46 -1.97]
 [-0.92  0.23  0.79  1.04  0.79]]
 
[[-0.39  2.75 -1.75 -0.92]
 [ 0.87 -1.9   2.81  0.28]
 [-0.78 -2.01 -1.36  1.29]
 [-0.44 -0.06 -1.09  0.28]
 [ 0.04  3.78 -0.99 -1.6 ]
 [-1.75 -1.14 -3.92  1.48]
 [-0.52 -0.01 -1.86  0.36]]


# Using pytorch

In [ ]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))